config/routes.rb
# frozen_string_literal: true

require "sidekiq/web"
require "staff_constraint"

Rails.application.routes.draw do
  mount Peek::Railtie => "/peek"
  mount ActionCable.server => "/cable"

  root to: "pages#home"

  get "/assistant", to: "pages#assistant"
  get "/home", to: "pages#homev2"

  get  "/login",  to: "sessions#new",     as: "login"
  post "/logout", to: "sessions#destroy", as: "logout"

  get  "/login/oauth/authorize", to: "oauth#authorize"
  post  "/login/oauth/access_token", to: "oauth#access_token"

  match "/auth/:provider/callback", to: "sessions#create",  via: %i[get post]
  match "/auth/failure",            to: "sessions#failure", via: %i[get post]

  get "/a/:short_key", to: "short_url#assignment_invitation",       as: "assignment_invitation_short"
  get "/g/:short_key", to: "short_url#group_assignment_invitation", as: "group_assignment_invitation_short"

  get "/autocomplete/github_repos", to: "autocomplete#github_repos"

  get "/boom", to: "site#boom_town"
  get "/boom/sidekiq", to: "site#boom_sidekiq"

  scope "github", as: "github" do
    constraints user_agent: %r{\AGitHub-Hookshot/\w+\z}, format: "json" do
      post :hooks, to: "hooks#receive"
    end
  end

  resources :assignment_invitations, path: "assignment-invitations", only: [:show] do
    member do
      patch :accept
      get   :setup
      post  :create_repo
      get   :progress
      get   :success
      patch :join_roster
    end
  end

  resources :group_assignment_invitations, path: "group-assignment-invitations", only: [:show] do
    member do
      get   :accept
      patch :accept_assignment
      patch :accept_invitation
      get   :setup
      post  :create_repo
      get   :progress
      get   :successful_invitation, path: :success
      patch :join_roster
    end
  end

  scope path_names: { edit: "settings" } do
    resources :organizations, path: "classrooms" do
      member do
        get   :invite
        get   :new_assignment, path: "new-assignment"
        get   :setup
        patch :setup_organization
        get   "settings/invitations", to: "organizations#invitation"
        get   "settings/teams",       to: "organizations#show_groupings"
        delete "users/:user_id",      to: "organizations#remove_user", as: "remove_user"

        resource :roster, only: %i[show new create], controller: "orgs/rosters" do
          patch :link
          patch :unlink
          patch :delete_entry
          patch :add_students
          patch :remove_organization
        end
      end

      resources :groupings, only: %i[show edit update] do
        resources :groups, only: [:show] do
          member do
            patch "/memberships/:user_id", to: "groups#add_membership", as: "add_membership"
            delete "/memberships/:user_id", to: "groups#remove_membership", as: "remove_membership"
          end
        end
      end

      resources :assignments do
        resources :assignment_repos, only: [:show], controller: "orgs/assignment_repos"
        get "/roster_entries/:roster_entry_id", to: "orgs/roster_entries#show", as: "roster_entry"
        get :assistant, on: :member
      end

      resources :group_assignments, path: "group-assignments" do
        resources :group_assignment_repos, only: [:show], controller: "orgs/group_assignment_repos"
        get "/roster_entries/:roster_entry_id", to: "orgs/roster_entries#show", as: "roster_entry"
        get :assistant, on: :member
      end
    end
  end

  resources :videos, only: [:index]

  namespace :stafftools do
    constraints StaffConstraint.new do
      mount Sidekiq::Web => "/sidekiq"
      mount Flipper::UI.app(GitHubClassroom.flipper) => "/flipper", as: "flipper"
    end

    root "resources#index", as: :root
    get "/resource_search", to: "resources#search"

    resources :users, only: [:show] do
      member do
        post :impersonate
        delete :stop_impersonating
      end
    end

    resources :organizations, path: "classrooms", only: [:show] do
      member do
        delete "/users/:user_id", to: "organizations#remove_user", as: "remove_user"
      end
    end

    resources :repo_accesses, only: [:show]

    resources :assignment_invitations, only: [:show]
    resources :assignment_repos,       only: %i[show destroy]
    resources :assignments,            only: [:show]

    resources :deadlines, only: [:show]

    resources :group_assignment_invitations, path: "group-assignment-invitations", only: [:show]
    resources :group_assignment_repos,       path: "group-assignment-repos",       only: %i[show destroy]
    resources :group_assignments,            path: "group-assignments",            only: [:show]

    resources :groupings, only: [:show]
    resources :groups,    only: [:show]
  end

  namespace :api, defaults: { format: :json } do
    scope :internal do
      resources :organizations, path: "classrooms", only: [:index] do
        resources :assignments, only: %i[index show] do
          resources :assignment_repos, only: [:index] do
            get "/clone_url", to: "assignment_repos#clone_url"
          end
        end
        resources :group_assignments, path: "group-assignments", only: %i[index show] do
          resources :group_assignment_repos, path: "group-assignment-repos", only: [:index] do
            get "/clone_url", to: "group_assignment_repos#clone_url"
          end
        end
      end
      get "/user", to: "users#authenticated_user"
    end
  end
end

app/models/roster.rb
# frozen_string_literal: true

class Roster < ApplicationRecord
  has_many :roster_entries
  has_many :organizations

  validates :identifier_name, presence: true
  validates :roster_entries, presence: true

  def unlinked_entries
    roster_entries.select do |entry|
      entry.user.nil?
    end
  end
end

app/models/roster/creator.rb
# frozen_string_literal: true

class Roster
  class Creator
    class Result
      class Error < StandardError; end

      def self.success(roster)
        new(:success, roster: roster)
      end

      def self.failed(roster, error)
        new(:failed, roster: roster, error: error)
      end

      attr_reader :error, :roster

      def initialize(status, roster: nil, error: nil)
        @status = status
        @roster = roster
        @error  = error
      end

      def success?
        @status == :success
      end

      def failed?
        @status == :failed
      end
    end

    # Public: Create a Roster for an Organiation.
    #
    # organization    - The Organization the Roster will belong to.
    # identifier_name - The name of the identifiers for the Roster.
    # options         - The Hash of options.
    #
    # Examples
    #
    #   Roster::Creator.perform(
    #     organization: current_organization,
    #     identifier_name: "Email",
    #     options
    #   )
    #
    # Returns an Roster::Creator::Result.
    def self.perform(organization:, identifier_name:, **options)
      new(organization: organization, identifier_name: identifier_name, **options).perform
    end

    def initialize(organization:, identifier_name:, **options)
      @organization    = organization
      @identifier_name = identifier_name
      @options         = options
    end

    # Internal: Create create a Roster.
    #
    def perform
      ensure_organization_does_not_have_roster!

      ActiveRecord::Base.transaction do
        @roster = Roster.new(identifier_name: @identifier_name)
        add_identifiers_to_roster(@options[:identifiers]) if @options.key?(:identifiers)

        @roster.save!
        @organization.update_attributes!(roster: @roster)
      end

      Result.success(@roster)
    rescue Result::Error, ActiveRecord::ActiveRecordError => err
      Result.failed(@roster, err.message)
    end

    private

    def add_identifiers_to_roster(raw_identifiers_string)
      identifiers = raw_identifiers_string.split("\r\n").reject(&:blank?).uniq
      identifiers.each do |identifier|
        @roster.roster_entries << RosterEntry.new(identifier: identifier)
      end
    end

    def ensure_organization_does_not_have_roster!
      raise Result::Error, "This organization already has a roster" unless @organization.roster.nil?
    end
  end
end

app/controllers/orgs/assignment_repos_controller.rb
# frozen_string_literal: true

module Orgs
  class AssignmentReposController < Orgs::Controller
    layout false

    def show
      @assignment_repo = AssignmentRepo.includes(:user).find_by!(id: params[:id], assignment: current_assignment)
    end

    private

    def current_assignment
      return @current_assignment if defined?(@current_assignment)
      @current_assignment = current_organization.assignments.find_by(slug: params[:assignment_id])
    end
  end
end

app/controllers/orgs/controller.rb
# frozen_string_literal: true

module Orgs
  class Controller < ApplicationController
    before_action :ensure_current_organization
    before_action :ensure_current_organization_visible_to_current_user

    protected

    def add_current_user_to_current_organization_or_404
      github_organization = GitHubOrganization.new(current_user.github_client, current_organization.github_id)
      return not_found unless github_organization.admin?(current_user.github_user.login)
      current_organization.users << current_user
      true
    end

    def ensure_current_organization
      not_found if current_organization.nil?
    end

    def ensure_current_organization_visible_to_current_user
      return true if current_organization.users.pluck(:id).include?(current_user.id)
      add_current_user_to_current_organization_or_404
    end

    def current_organization
      return @current_organization if defined?(@current_organization)
      organization_id = params[:organization_id] || params[:id]
      @current_organization = Organization.find_by!(slug: organization_id)
    end
    helper_method :current_organization

    def failbot_context
      super unless current_organization.nil?
      super.merge(organization: current_organization.id)
    end
  end
end

app/controllers/orgs/group_assignment_repos_controller.rb
# frozen_string_literal: true

module Orgs
  class GroupAssignmentReposController < Orgs::Controller
    layout false

    def show
      @group_assignment_repo = GroupAssignmentRepo.includes(:group).find_by!(
        id: params[:id],
        group_assignment: current_group_assignment
      )
    end

    private

    def current_group_assignment
      return @current_assignment if defined?(@current_assignment)
      @current_assignment = current_organization.group_assignments.find_by(slug: params[:group_assignment_id])
    end
  end
end

app/controllers/orgs/roster_entries_controller.rb
# frozen_string_literal: true

module Orgs
  class RosterEntriesController < Orgs::Controller
    before_action :ensure_current_assignment
    before_action :ensure_current_roster
    before_action :ensure_current_roster_entry

    helper_method :current_assignment_repo, :current_roster_entry

    layout false

    def show
      if current_assignment_repo
        render partial: "orgs/roster_entries/assignment_repos/linked_accepted",
               locals: { assignment_repo: current_assignment_repo }
      elsif current_roster_entry.user
        render partial: "orgs/roster_entries/assignment_repos/linked_not_accepted"
      else
        render partial: "orgs/roster_entries/assignment_repos/not_in_classroom"
      end
    end

    private

    def current_assignment
      return @current_assignment if defined?(@current_assignment)
      @current_assignment = if params[:assignment_id]
                              current_organization.assignments.find_by(slug: params[:assignment_id])
                            else
                              current_organization.group_assignments.find_by(slug: params[:group_assignment_id])
                            end
    end

    def current_assignment_repo
      return @current_assignment_repo if defined?(@current_assignment_repo)
      return @current_assignment_repo = nil if current_roster_entry.user.nil?
      @current_assignment_repo = find_current_assignment_repo
    end

    def current_roster
      return @current_roster if defined?(@current_roster)
      @current_roster = current_organization.roster
    end

    def current_roster_entry
      return @current_roster_entry if defined?(@current_roster_entry)
      current_roster.roster_entries.find(params[:roster_entry_id])
    end

    def ensure_current_assignment
      not_found if current_assignment.nil?
    end

    def ensure_current_roster
      not_found if current_roster.nil?
    end

    def ensure_current_roster_entry
      not_found if current_roster_entry.nil?
    end

    def find_assignment_repo
      current_assignment.repos.find_by(user: current_roster_entry.user)
    end

    def find_current_assignment_repo
      return find_assignment_repo if current_assignment.is_a?(Assignment)
      find_group_assignment_repo
    end

    def find_group_assignment_repo
      current_assignment.repos.select do |repo|
        repo.repo_accesses.map(&:user).include?(current_roster_entry.user)
      end.first
    end
  end
end

app/views/orgs/rosters/_delete_roster_entry_modal.html.erb
<div class="remodal text-left" data-remodal-id="delete-entry-<%= roster_entry.id %>">
  <button data-remodal-action="close" class="remodal-close"><%= octicon 'x' %></button>
  <h2 class="remodal-header text-left">Are you sure you want to delete this?</h2>

  <div class="remodal-warning">
    Unexpected things will happen if you don't read this!
  </div>

  <div class="remodal-description">
    This action will delete the student from your roster. This will unlink any GitHub accounts connected to this student.
  </div>

  <%= form_tag({ controller: :rosters, action: :delete_entry }, method: :patch) do %>
    <%= hidden_field_tag 'roster_entry_id', roster_entry.id %>
    <%= submit_tag 'Delete this student', class: 'btn btn-danger btn-block js-submit' %>
  <% end %>
</div>

app/views/orgs/rosters/_download_csv_modal.html.erb
<div class="remodal text-left" data-remodal-id="download-csv-modal">
 <button data-remodal-action="close" class="remodal-close"><%= octicon 'x' %></button>
  <h2 class="remodal-header text-left">Select a Grouping</h2>

  <div class="remodal-user-list">
    <%= link_to 'Download without group names', roster_path(format: :csv), class: 'btn btn-primary btn-sm btn-block remodal-button' %>
    <% organization.groupings.map do |grouping| %>
        <%= link_to(
            "Download #{grouping.title}",
            roster_path(grouping: grouping.id, format: :csv),
            class: 'btn btn-sm btn-block remodal-button'
          )
        %>
    <% end %>
  </div>
</div>

app/views/orgs/rosters/_link_to_github_account_modal.html.erb
<div class="remodal text-left" data-remodal-id="link-to-github_account-<%= roster_entry.id %>">
  <button data-remodal-action="close" class="remodal-close"><%= octicon 'x' %></button>
  <h2 class="remodal-header text-left">Select a GitHub account to link with</h2>

  <p>
    <strong>Select an unlinked GitHub account to link this student to:</strong>
  </p>
  <div class="remodal-user-list">
    <% unlinked_users.each do |user| %>
      <div class="remodal-user">
        <%= form_tag({ controller: :rosters, action: :link }, method: :patch) do %>
          <%= hidden_field_tag 'user_id', user.id %>
          <%= hidden_field_tag 'roster_entry_id', roster_entry.id %>
          <%= submit_tag ('@' + user.github_user.login), class: 'remodal-user' %>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/orgs/rosters/_link_to_student_modal.html.erb
<div class="remodal text-left" data-remodal-id="link-to-student-<%= user.id %>">
  <button data-remodal-action="close" class="remodal-close"><%= octicon 'x' %></button>
  <h2 class="remodal-header text-left">Select a student to link with</h2>

  <p>
    <strong>Select a student from your roster to link this GitHub account to</strong>
  </p>
  <div class="remodal-user-list">
    <% unlinked_entries.each do |entry| %>
      <div class="remodal-user">
        <%= form_tag({ controller: :rosters, action: :link }, method: :patch) do %>
          <%= hidden_field_tag 'user_id', user.id %>
          <%= hidden_field_tag 'roster_entry_id', entry.id %>
          <%= submit_tag entry.identifier, class: 'remodal-user' %>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/orgs/rosters/_new_student_modal.html.erb
<div class="remodal text-left" data-remodal-id="new-student-modal">
  <button data-remodal-action="close" class="remodal-close"><%= octicon 'x' %></button>
  <h2 class="remodal-header text-left">Add students to your Roster</h2>

  <%= form_tag({ controller: :rosters, action: :add_students }, method: :patch) do %>
    <dl class="form">
      <dt><label><%= roster.identifier_name.pluralize %></label></dt>
      <%= text_area_tag 'identifiers', '', class: "form-control input-block", id: 'entries-field' %>
    </dl>

    <dl class="form">
      <dt><label>OR upload a CSV or text file:</label></dt>
      <label class='btn btn-secondary btn-sm' for="file-upload">Upload file</label>
      <%= file_field_tag :identifiers_file, style: 'display: none', id: 'file-upload', onchange: 'onIdentifiersUploaded()' %>
    </dl>

    <div class="form-actions">
      <%= submit_tag 'Create students', class: "btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/orgs/rosters/_remove_roster_modal.html.erb
<div class="remodal text-left" data-remodal-id="remove-roster">
  <button data-remodal-action="close" class="remodal-close"><%= octicon 'x' %></button>
  <h2 class="remodal-header text-left">Are you sure you want to delete this roster?</h2>

  <div class="remodal-warning">
    Unexpected things will happen if you don't read this!
  </div>

  <div class="remodal-description">
    Deleting the roster will delete all students.
    This will not delete assignments, assignment repos, or submissions.
    After deleting your roster, repos and submissions will be identified by GitHub handle instead of your roster identifier.
  </div>

  <%= form_tag({ controller: :rosters, action: :remove_organization }, method: :patch) do %>
    <%= submit_tag 'Delete roster', class: 'btn btn-danger btn-block js-submit' %>
  <% end %>
</div>

app/views/orgs/rosters/_roster_entry.html.erb
<% view = RosterEntry::ShowView.new(roster_entry: roster_entry) %>

<div class="assignment-list-item d-flex col-12">
  <div class="col-6 d-flex fixed-height-row">
    <div class="d-flex flex-column flex-justify-center flex-items-center flex-md-items-start">
      <span class="assignment-icon assignment-icon-individual left">
        <% if view.linked? %>
          <%= image_tag view.github_avatar_url, height: 46, width: 46, class: 'avatar left' %>
        <% else %>
          <%= octicon 'person', height: 22 %>
          <% end %>
      </span>
    </div>

    <div class="flex-column">
      <h4 class="assignment-name-link">
        <%= view.identifier %>
      </h4>

      <p class="assignment-type text-gray">
        <% if view.linked? %>
          <a class="" href='<%= view.github_profile_url %>'>
            <%= view.github_handle_text %>
          </a>
        <% else %>
          Unlinked user
        <% end %>
      </p>
    </div>
  </div>

  <div class="d-flex right-button">
    <div class="flex-self-center input-group ">
      <% if view.linked? %>
        <%= form_tag({ controller: :rosters, action: :unlink }, method: :patch, class: "d-inline") do %>
          <%= hidden_field_tag 'roster_entry_id', roster_entry.id %>
          <%= submit_tag 'Unlink GitHub account', class: view.button_class %>
        <% end %>
      <% else %>
        <a class="btn btn-outline", data-remodal-target="link-to-github_account-<%= roster_entry.id %>">Link to GitHub account</a>
      <% end %>
      <span class='clickable' data-remodal-target="delete-entry-<%= roster_entry.id %>">
        <%= octicon 'x', height: 22, class: "remove-roster-entry-button" %>
      </span>
    </div>
  </div>
</div>

<%= render partial: 'link_to_github_account_modal', locals: { roster_entry: roster_entry } %>
<%= render partial: 'delete_roster_entry_modal', locals: { roster_entry: roster_entry } %>

app/views/orgs/rosters/_unlinked_user.html.erb
<% view = User::UnlinkedUser::ShowView.new(unlinked_user: unlinked_user) %>

<div class="assignment-list-item d-flex col-12">
  <div class="col-6 d-flex flex-items-center fixed-height-row">
    <div class="d-flex flex-column flex-justify-center flex-items-center flex-md-items-start">
      <span class="left assignment-icon">
        <%= image_tag view.github_avatar_url, height: 46, width: 46, class: 'avatar left' %>
      </span>
    </div>
    <a class='student-login' href="<%= view.github_url %>">
      <h4><%= view.github_handle_text %></h4>
    </a>
  </div>

  <div class="d-flex right-button">
    <div class="flex-self-center input-group ">
      <a class="btn btn-outline", data-remodal-target="link-to-student-<%= unlinked_user.id %>">Link to student</a>
    </div>
  </div>
</div>

<%= render partial: 'link_to_student_modal', locals: { user: unlinked_user, unlinked_entries: current_roster.unlinked_entries } %>

app/views/orgs/rosters/new.html.erb
<% view = FormView.new(subject: @roster) %>

<div class="site-content">
  <div class="site-content-cap">
    <h2 class="site-content-heading">Add students</h2>
  </div>
  <div class="site-content-body">
    <div class="markdown-body">
      <p> Next, let's set up a "roster", so you can easily track student progress on your dashboard.
      <p> To create your roster, you'll need to share a way to identify your students. These "identifiers" can be:</p>

      <ul>
        <li>Student last names</li>
        <li>Student email addresses</li>
        <li>Any other unique piece of information</li>
      </ul>

      <p>You can always come back and complete this step later.</p>
    </div>
    </br>
    <div>
      <%= form_tag roster_path(current_organization), method: :post do |f| %>
        <dl class="<%= view.form_class_for(:identifier_name) %> short-field">
          <dt><label>What information would you like to use to identify your students?</br> (emails, student ID #, etc.)</label></dt>
          <dd><%= text_field_tag(:identifier_name, '', class: 'form-control input-block', required: true) %></dd>
          <%= render('shared/form_error', errors: view.error_message_for(:identifier_name)) if view.errors_for?(:identifier_name) %>
        </dl>

        <dl class="<%= view.form_class_for(:roster_entries) %> short-field">
          <dt><label>Paste your list of identifiers below (one per line, please!):</label></dt>
          <dd><%= text_area_tag(:identifiers, '', class: 'form-control input-block', id: 'entries-field', required: true) %></dd>
          <%= render('shared/form_error', errors: view.error_message_for(:roster_entries)) if view.errors_for?(:roster_entries) %>
        </dl>

        <dl class="form">
          <dt><label>OR upload a CSV or text file:</label></dt>
          <label class='btn btn-secondary btn-sm' for="file-upload">Upload file</label>
          <%= file_field_tag :identifiers_file, style: 'display: none', id: 'file-upload', onchange: 'onIdentifiersUploaded()' %>
        </dl>

        <div class="form-actions">
          <%= submit_tag 'Create roster', class: 'btn btn-primary right' %>
          <%= link_to 'Skip', organization_path(current_organization), class: 'btn btn-secondary right' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/orgs/rosters/show.html.erb
<div class="remodal-bg">
  <%= render 'organizations/organization_banner' %>

  <div class="columns">
    <div class="one-fourth column">
      <%= render partial: 'organizations/side_menu' %>
    </div>
    <div class="three-fourths column">
      <div class="boxed-group">
        <h3 class='d-flex flex-justify-between flex-items-center'>
          <span>
            Classroom roster
          </span>
          <div class='flex-justify-between'>
            <span class="btn btn-primary btn-sm", role="button" data-remodal-target="new-student-modal">New students</span>
             <span class="btn btn-primary btn-sm", role="button" data-remodal-target="download-csv-modal">Download</span>
          </div>
        </h3>

        <div class="site-content-body tabnav-body clearfix">
          <div class="tabnav">
            <nav class="tabnav-tabs">
              <span id='students-tab' onclick="selectTab(this)" class="tabnav-tab selected tabnav-link" aria-current="page">All students</span>
              <span id='unlinked-tab' onclick="selectTab(this)" class="tabnav-tab tabnav-link">Unlinked GitHub accounts</span>
            </nav>
          </div>
          <span id='students-span'>
            <div class="assignment-list-items">
              <% @roster_entries.each do |roster_entry| %>
                <%= render 'roster_entry', roster_entry: roster_entry %>
              <% end %>

              <div class="d-flex col-12">
                <%= render partial: 'shared/pagination', locals: { collection: @roster_entries, param_name: :roster_entries_page } %>
              </div>
            </div>
          </span>
          <span id='unlinked-span' class='hidden-tab'>
            <div class="assignment-list-items">
              <% if unlinked_users.empty? %>
                <%= render 'shared/unlinked_blank_slate' %>
              <% else %>
                <% @current_unlinked_users.each do |user| %>
                  <%= render 'unlinked_user', unlinked_user: user %>
                <% end %>

                <div class="d-flex col-12">
                  <%= render partial: 'shared/pagination', locals: { collection: @current_unlinked_users, param_name: :unlinked_users_page } %>
                </div>
              <% end %>
            </div>
          </span>
        </div>
      </div>

      <div class="boxed-group dangerzone">
        <h3>Delete this roster</h3>
        <div class="boxed-group-inner pt-2 clearfix">
          <p>
            Deleting the roster will delete all students.
          </p>
          <p>
            This will not delete assignments, assignment repos, or submissions.
          </p>
            After deleting your roster, repos and submissions will be identified by GitHub handle instead of your roster identifier.
          </p>
          <p>
            <a data-remodal-target="remove-roster" class="btn btn-danger">Delete roster</a>
          </p>
        </div>
      </div>
    </div>
  </div>
</div>

<%= render partial: 'new_student_modal', locals: { roster: current_roster } %>
<%= render partial: 'download_csv_modal', locals: { roster: current_roster, organization: current_organization } %>
<%= render partial: 'remove_roster_modal', locals: { roster: current_roster, organization: current_organization } %>